version: 2
jobs:
  build:
     docker:
       - image: circleci/python:3.6.4
     steps:
     - checkout
     - run:
          command: |
            set -e
            mkdir results
            pip freeze > results/pythonpackages.txt
            grep "html-linter==0.4.0" pythonpackages.txt # to show how you could check versions
            html_lint.py --disable=optional_tag site/index.html # static website test
     - store_artifacts:
         path: results          

