version: 2
jobs:
  build:
     docker:
       - image: circleci/python:3.6.4
     steps:
     - checkout
     - run:
          command: |
            set -e
            mkdir results
            sudo pip install -r requirements.txt  
            pip freeze > results/pythonpackages.txt
            grep "html-linter==0.4.0" results/pythonpackages.txt # to show how you could check versions
            python /usr/local/lib/python3.6/site-packages/html_linter.py --disable=optional_tag site/index.html # static website test
     - store_artifacts:
         path: results 
         
  deploy-job:
    docker:
       - image: circleci/python:3.6.4
    steps:
     - run: sudo pip install awscli --upgrade --user
     - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync site s3://demo2.d1g.nl --delete --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
