version: 2
jobs:
  build:
     docker:
       - image: circleci/python:3.6.4
     steps:
     - checkout
     - run:
          command: |
            set -e
            mkdir results
            echo foo > results/pythonpackages.txt
            sudo pip install -r requirements.txt  
            pip freeze 
            grep "html-linter==0.4.0" results/pythonpackages.txt # to show how you could check versions
            python html_lint.py --disable=optional_tag site/index.html # static website test
     - store_artifacts:
         path: results          

